name: "Ultra-Advanced iOS Build & IPA Pipeline"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 90
    env:
      # General project settings
      PROJECT_NAME: "Stay"
      SCHEME_NAME: "Stay"
      CONFIGURATION: "Release"
      SDK: "iphoneos"
      DERIVED_DATA: "build"
      IPA_NAME: "Stay-unsigned.ipa"
      BINARY_URL: "https://github.com/arthenica/ffmpeg-kit/releases/download/v6.0/ffmpeg-kit-full-6.0-ios-xcframework.zip"
      DOWNLOADS_DIR: "Downloads"

    steps:
      - name: Download and Unzip Repository Archive
        run: |
          echo "Downloading repository archive from https://files.catbox.moe/j4y5cd.zip..."
          curl -L -o stay.zip https://files.catbox.moe/j4y5cd.zip
          echo "Downloaded as stay.zip. Unzipping..."
          unzip stay.zip
          echo "Unzip complete. Listing directory contents:"
          ls -la

      - name: Set Up Ruby Environment
        run: |
          echo "Installing/updating Ruby via Homebrew..."
          brew install ruby || echo "Ruby already installed"
          echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile
          source ~/.bash_profile
          ruby -v

      - name: Install CocoaPods
        run: |
          echo "Installing CocoaPods..."
          sudo gem install cocoapods || (echo "CocoaPods install failed" && exit 1)
          pod --version

      - name: Update pod repos
        working-directory: ./Stay
        run: |
          echo "update pod repos..."
          pod repo update

      - name: Install Pods
        working-directory: ./Stay
        run: |
          echo "Running pod install..."
          pod install --verbose || { echo "pod install failed"; exit 1; }

      - name: Build iOS App
        working-directory: ./Stay
        run: |
          echo "Starting build using xcodebuild..."
          xcodebuild -workspace "$PROJECT_NAME.xcworkspace" \
            -scheme "$SCHEME_NAME" \
            -configuration "$CONFIGURATION" \
            -sdk "$SDK" \
            -derivedDataPath "$DERIVED_DATA" \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
            || { echo "xcodebuild failed. Dumping build logs:"; exit 1; }
          echo "Build completed successfully."

      - name: Package Unsigned IPA
        working-directory: ./Stay
        run: |
          echo "Packaging app into IPA..."
          mkdir -p Payload
          APP_PATH="$DERIVED_DATA/Build/Products/$CONFIGURATION-iphoneos/$PROJECT_NAME.app"
          if [ -d "$APP_PATH" ]; then
            cp -R "$APP_PATH" Payload/
          else
            echo "ERROR: App bundle not found at expected path: $APP_PATH"
            exit 1
          fi
          cd Payload && zip -r ../"$IPA_NAME" . && cd ..
          echo "IPA package created successfully: $(ls -lh "$IPA_NAME")"

      - name: Upload IPA via curl to bashupload.com
        working-directory: ./Stay
        run: |
          echo "Uploading IPA to bashupload.com..."
          IPA_LINK=$(curl --fail -L bashupload.com -T "$IPA_NAME")
          if [ -z "$IPA_LINK" ]; then
            echo "ERROR: Upload failed; no link returned."
            exit 1
          else
            echo "IPA successfully uploaded. Link: ${IPA_LINK}"
          fi

      - name: Upload IPA as Build Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: $IPA_NAME
          path: ./Stay/"$IPA_NAME"
