name: "build"

# This workflow is manually triggered.
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 90
    env:
      # General project settings
      PROJECT_NAME: "Stay"
      SCHEME_NAME: "Stay"
      CONFIGURATION: "Release"
      SDK: "iphoneos"
      DERIVED_DATA: "build"
      IPA_NAME: "Stay-unsigned.ipa"
      # URL for the ffmpeg-kit binary (version 5.1)
      BINARY_URL: "https://github.com/arthenica/ffmpeg-kit/releases/download/v5.1/ffmpeg-kit-full-5.1-ios-xcframework.zip"
      DOWNLOADS_DIR: "Downloads"
      LOCAL_PODSPEC: "ffmpeg-kit-ios-full.podspec"
      # (Optional) Code signing variables – these must be set as repository secrets if used.
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      CERTIFICATE: ${{ secrets.CERTIFICATE_BASE64 }}
      CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}

    steps:
      - name: Clone External Repository
        run: |
          echo "Cloning external repository from https://github.com/shenruisi/Stay.git (branch: turbe-engine)..."
          rm -rf Stay || true
          git clone --branch turbe-engine https://github.com/shenruisi/Stay.git
          cd Stay
          echo "Repository cloned. Current directory contents:"
          ls -la

      - name: Set Up Ruby Environment
        run: |
          echo "Installing/updating Ruby via Homebrew..."
          brew install ruby || echo "Ruby already installed"
          echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile
          source ~/.bash_profile
          ruby -v

      - name: Install CocoaPods
        run: |
          echo "Installing CocoaPods..."
          sudo gem install cocoapods || (echo "CocoaPods install failed" && exit 1)
          pod --version

      - name: Clean Previous Build & Pod Artifacts
        working-directory: ./Stay
        run: |
          echo "Cleaning previous Pods, lockfiles, build data, and IPA..."
          rm -rf Pods
          rm -rf "$DERIVED_DATA"
          rm -f Podfile.lock
          rm -f "$IPA_NAME"

      - name: Install Pods with Comprehensive Fallback
        working-directory: ./Stay
        shell: bash
        run: |
          set -eo pipefail
          echo "Starting pod install..."
          # Try a normal install with retries
          RETRIES=0
          MAX_RETRIES=3
          until pod install --verbose; do
            RETRIES=$((RETRIES+1))
            echo "pod install failed. Retry attempt ${RETRIES} of ${MAX_RETRIES}..."
            if [ $RETRIES -ge $MAX_RETRIES ]; then
              echo "Normal pod install failed after $RETRIES attempts. Initiating fallback workaround."
              break
            fi
            sleep 10
          done
          
          if [ $RETRIES -ge $MAX_RETRIES ]; then
            echo "Manual fallback: Download and override dependency for ffmpeg-kit-ios-full."
            # Create a clean downloads directory.
            mkdir -p "$DOWNLOADS_DIR"
            OUTPUT_FILE="$DOWNLOADS_DIR/ffmpeg-kit-full-5.1-ios-xcframework.zip"
            echo "Attempting manual download from $BINARY_URL..."
            if curl -L -o "$OUTPUT_FILE" "$BINARY_URL"; then
              echo "Download succeeded. File details:"
              ls -lh "$OUTPUT_FILE"
            else
              echo "ERROR: Manual download failed. Aborting."
              exit 1
            fi

            echo "Generating local Podspec override file: $LOCAL_PODSPEC..."
            cat <<'EOF' > "$LOCAL_PODSPEC"
Pod::Spec.new do |s|
  s.name         = 'ffmpeg-kit-ios-full'
  s.version      = '5.1'
  s.summary      = 'FFmpegKit iOS full binary'
  s.homepage     = 'https://github.com/arthenica/ffmpeg-kit'
  s.license      = { :type => 'LGPL', :file => 'LICENSE' }
  s.author       = { 'Taner Şener' => 'tanersener@gmail.com' }
  s.platform     = :ios, '15.0'
  s.source       = { :http => "file://$(pwd)/$DOWNLOADS_DIR/ffmpeg-kit-full-5.1-ios-xcframework.zip" }
  s.vendored_frameworks = 'ffmpeg-kit-full.xcframework'
end
EOF
            echo "Local Podspec created:"
            cat "$LOCAL_PODSPEC"

            echo "Patching Podfile to force use of local Podspec..."
            # If not already patched, insert a fallback pod line after the target declaration.
            if ! grep -q "ffmpeg-kit-ios-full fallback override" Podfile; then
              sed -i '' '/^target /a\
  pod '\''ffmpeg-kit-ios-full'\'', :podspec => '\''./ffmpeg-kit-ios-full.podspec'\'', # ffmpeg-kit-ios-full fallback override
' Podfile
              echo "Podfile patched successfully."
            else
              echo "Podfile already contains fallback override."
            fi

            echo "Re-running pod install with fallback override..."
            pod install --verbose || { echo "pod install still failing after fallback"; exit 1; }
          else
            echo "pod install completed successfully via normal process."
          fi

      - name: (Optional) Configure Code Signing Environment
        working-directory: ./Stay
        if: env.KEYCHAIN_PASSWORD != ''
        run: |
          echo "Configuring custom keychain for code signing..."
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          echo "Importing certificate..."
          echo "$CERTIFICATE" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          echo "Installing provisioning profile..."
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: Build iOS App
        working-directory: ./Stay
        run: |
          echo "Starting build using xcodebuild..."
          xcodebuild -workspace "$PROJECT_NAME.xcworkspace" \
            -scheme "$SCHEME_NAME" \
            -configuration "$CONFIGURATION" \
            -sdk "$SDK" \
            -derivedDataPath "$DERIVED_DATA" \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
            || { echo "xcodebuild failed. Dumping build logs:"; exit 1; }
          echo "Build completed successfully."

      - name: Package Unsigned IPA
        working-directory: ./Stay
        run: |
          echo "Packaging app into IPA..."
          mkdir -p Payload
          APP_PATH="$DERIVED_DATA/Build/Products/$CONFIGURATION-iphoneos/$PROJECT_NAME.app"
          if [ -d "$APP_PATH" ]; then
            cp -R "$APP_PATH" Payload/
          else
            echo "ERROR: App bundle not found at expected path: $APP_PATH"
            exit 1
          fi
          cd Payload && zip -r ../"$IPA_NAME" . && cd ..
          echo "IPA package created successfully: $(ls -lh "$IPA_NAME")"

      - name: Upload IPA via curl to bashupload.com
        working-directory: ./Stay
        run: |
          echo "Uploading IPA to bashupload.com..."
          IPA_LINK=$(curl --fail -L bashupload.com -T "$IPA_NAME")
          if [ -z "$IPA_LINK" ]; then
            echo "ERROR: Upload failed; no link returned."
            exit 1
          else
            echo "IPA successfully uploaded. Link: ${IPA_LINK}"
          fi

      - name: Upload IPA as Build Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: $IPA_NAME
          path: ./Stay/"$IPA_NAME"

      - name: Final Cleanup
        working-directory: ./Stay
        run: |
          echo "Performing cleanup..."
          [ -f certificate.p12 ] && rm certificate.p12
          [ -d "$DOWNLOADS_DIR" ] && rm -rf "$DOWNLOADS_DIR"
          [ -f "$LOCAL_PODSPEC" ] && rm "$LOCAL_PODSPEC"
          rm -rf Payload
          # Optionally delete the custom keychain if it was created.
          security delete-keychain build.keychain || echo "Keychain already deleted."
          echo "Cleanup complete."
