name: iOS Build and IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone external repository
        run: |
          git clone --branch turbe-engine https://github.com/shenruisi/Stay.git

      - name: Patch ffmpeg-kit dependency in Podfile
        working-directory: ./Stay
        run: |
          echo "Patching ffmpeg-kit-ios-full version from 5.1 to 5.1.1 in Podfile..."
          sed -i '' "s/'ffmpeg-kit-ios-full', '5\.1'/'ffmpeg-kit-ios-full', '5.1.1'/g" Podfile || echo "No patch needed or pattern not found."

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        working-directory: ./Stay
        run: pod install --verbose

      - name: Build iOS app (Release scheme)
        working-directory: ./Stay
        run: |
          xcodebuild -workspace "Stay.xcworkspace" \
            -scheme "Stay" \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""

      - name: Package unsigned IPA
        working-directory: ./Stay
        run: |
          mkdir -p Payload
          cp -R build/Build/Products/Release-iphoneos/Stay.app Payload/
          cd Payload && zip -r ../Stay-unsigned.ipa . && cd ..

      - name: Upload IPA to bashupload.com
        working-directory: ./Stay
        run: |
          echo "Uploading IPA to bashupload.com..."
          IPA_LINK=$(curl bashupload.com -T Stay-unsigned.ipa)
          echo "IPA uploaded: ${IPA_LINK}"

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: Stay-unsigned.ipa
          path: ./Stay/Stay-unsigned.ipa
